# Generated by Django 4.1.4 on 2024-05-15 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0051_cart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
