# Generated by Django 4.1.4 on 2024-05-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0054_student_wishlist_alter_student_emailid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="this_course_includes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="what_you_will_learn",
            field=models.TextField(blank=True, null=True),
        ),
    ]
