# Generated by Django 4.1.4 on 2024-05-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0055_course_this_course_includes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
