# Generated by Django 4.1.4 on 2024-05-15 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0056_course_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="timestamp",
        ),
    ]
