# Generated by Django 4.1.4 on 2024-05-17 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0059_remove_course_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("Payment Methods", "Payment Methods"),
                            ("Refund a Course", "Refund a Course"),
                            (
                                "Troubleshoot Payment Failure",
                                "Troubleshoot Payment Failure",
                            ),
                            ("Download Course Resources", "Download Course Resources"),
                            ("Enrollment", "Enrollment"),
                            ("Grades & Assignments", "Grades & Assignments"),
                            ("Video Library", "Video Library"),
                            ("Trust & Safety", "Trust & Safety"),
                            ("Find a missing course", "Find a missing course"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="tickets/"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Open", max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
