# Generated by Django 4.1.4 on 2024-05-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0062_remove_course_course_video_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="video",
            new_name="video_file",
        ),
        migrations.AddField(
            model_name="topic",
            name="video_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
