# Generated by Django 4.1.4 on 2024-05-23 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0065_certificate_quiz_quizquestion_questionpaper_grade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grade",
            name="certificate",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="course",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="quizquestion",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="quizresult",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="quizresult",
            name="student",
        ),
        migrations.RemoveField(
            model_name="selectedanswer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="selectedanswer",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="selectedanswer",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentcourseprogress",
            name="completed_weeks",
        ),
        migrations.RemoveField(
            model_name="studentcourseprogress",
            name="course",
        ),
        migrations.RemoveField(
            model_name="studentcourseprogress",
            name="student",
        ),
        migrations.RemoveField(
            model_name="questionpaper",
            name="grade",
        ),
        migrations.DeleteModel(
            name="Certificate",
        ),
        migrations.DeleteModel(
            name="Grade",
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
        migrations.DeleteModel(
            name="QuizQuestion",
        ),
        migrations.DeleteModel(
            name="QuizResult",
        ),
        migrations.DeleteModel(
            name="SelectedAnswer",
        ),
        migrations.DeleteModel(
            name="StudentCourseProgress",
        ),
    ]
