# Generated by Django 5.0.6 on 2024-05-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_topic_watched_by_users_certificate_grade_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
