# Generated by Django 5.0.6 on 2024-05-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_questionpaper_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedanswer',
            name='selected_option',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
